dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  # https://github.com/sdispater/poetry/issues/613
  # - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3 - --preview --yes
  # - source $HOME/.poetry/env
  - pip install --upgrade pip coveralls tox tox-travis poetry
script:
  - tox
after_success:
  - coveralls
notifications:
  email: false
