language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
env:
  global:
    - NEWEST_PYTHON=3.7
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - make lint
  - make type-check
  - make test
after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then
      pip install python-coveralls && coveralls
    fi
notifications:
  email: false
