# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import sys
import datetime as dt
from collections import OrderedDict
from pathlib import Path
sys.path.insert(0, str(Path('..').resolve()))

import layabout  # noqa


# -- Project information -----------------------------------------------------

changelog_mtime = Path('../CHANGELOG.rst').stat().st_mtime
copyright_year = dt.datetime.utcfromtimestamp(changelog_mtime)
homepage = 'https://tuckersiemens.com'

project = 'layabout'
author = 'Reilly Tucker Siemens'
copyright = f'{copyright_year:%Y}, <a href="{homepage}">{author}</a>'

# The short X.Y version
version = '.'.join(layabout.__version__.split('.')[0:2])
# The full version, including alpha/beta/rc tags
release = layabout.__version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.intersphinx',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
    'sphinx_autodoc_typehints',
]

intersphinx_mapping = {
    'python': ('http://python.readthedocs.io/en/latest/', None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

html_show_sourcelink = False

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'github_user': 'reillysiemens',
    'github_repo': 'layabout',
    'github_type': 'star',
    'note_bg': '#FFF59C',
    # Used to populate the useful-links.html template.
    'extra_nav_links': OrderedDict([
        ('Layabout @ PyPI', 'https://pypi.org/project/layabout/'),
        ('Layabout @ GitHub', 'https://github.com/reillysiemens/layabout/'),
        ('Issue Tracker', 'https://github.com/reillysiemens/layabout/issues/'),
        ('Slack RTM API Docs', 'https://api.slack.com/rtm'),
    ]),
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
    'index': [
        'about.html', 'sidebar.html', 'useful-links.html', 'searchbox.html',
    ],
    '**': [
        'about.html', 'sidebar.html', 'useful-links.html', 'localtoc.html',
        'relations.html', 'searchbox.html',
    ],
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'layaboutdoc'

# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
